language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules
before_install:
    - npm install

node_js:
  - "6"
  - "node"

script:
  - npm run standard
  - npm run test
  - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
