language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules
before_install:
    - npm install
    - npm install -g codecov

node_js:
  - "8"
  - "node"

script:
  - npm run standard
  - npm run test
  - npm run test-cov

after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
